---
- name: "Assert that all needed variables are defined"
  assert:
    that:
      - gitlab_api_url is defined
      - gitlab_api_token is defined
      - gitlab_project is defined
      - gitlab_validate_certs is defined
      - gitlab_api_user is defined
      - gitlab_default_branch is defined
      - gitlab_http_protocol is defined

- name: Set Git repo URL
  set_fact:
    gitlab_api_url: "{{ gitlab_http_protocol }}://{{ gitlab_api_user }}:{{ gitlab_api_token }}@{{ gitlab_api_url | regex_replace('http://|https://','') }}"

- name: Get Git repo ID
  ansible.builtin.uri:
    url: "{{ gitlab_api_url }}/api/v4/projects?search={{ gitlab_project_creation.project.path }}"
    method: GET
    status_code: 200
    return_content: true
    validate_certs: false
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
      Content-Type: application/json
  register: repo_id_res

- name: Create an access token for the given project
  ansible.builtin.uri:
    url: "{{ gitlab_api_url }}/api/v4/projects/{{ repo_id_res.json[0].id }}/access_tokens/"
    method: POST
    status_code: 201
    body_format: json
    body:
      name: "CasC deploy token"
      expires_at: "3000-01-01"
      access_level: 50
      scopes:
        - api
        - read_repository
    return_content: true
    validate_certs: false
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
      Content-Type: application/json
  register: repo_token_res

- name: Create the output artifacts
  ansible.builtin.set_stats:
    aggregate: true
    data:
      repo_token: "{{ repo_token_res.json.token }}"
...
