- name: "Assert that all needed variables are defined"
  assert:
    that:
      - gitlab_api_url is defined
      - gitlab_api_token is defined
      - gitlab_project is defined
      - gitlab_validate_certs is defined
      - gitlab_branches is defined

- name: Create branch from {{ gitlab_default_branch }}
  community.general.gitlab_branch:
    api_url: "{{ gitlab_api_url }}"
    validate_certs: "{{ gitlab_validate_certs }}"
    api_token: "{{  gitlab_api_token }}"
    project: "{{ ( gitlab_group +'/' ) if gitlab_group is defined else gitlab_api_user + '/' }}{{ ( gitlab_subgroup +'/' ) if gitlab_subgroup is defined else '' }}{{ gitlab_project }}"
    branch: "{{ __gitlab_branches_item }}"
    ref_branch: "{{ gitlab_default_branch }}"
    state: present

- name: Create protected branch on env branches
  community.general.gitlab_protected_branch:
    api_url: "{{ gitlab_api_url }}"
    validate_certs: "{{ gitlab_validate_certs }}"
    api_token: "{{  gitlab_api_token }}"
    project: "{{ ( gitlab_group +'/' ) if gitlab_group is defined else gitlab_api_user + '/' }}{{ (gitlab_subgroup + '/') if gitlab_subgroup is defined else '' }}{{ gitlab_project }}"
    name: "{{ __gitlab_branches_item }}"
    merge_access_levels: maintainer
    push_access_level: nobody
