---
- name: "Assert that all needed variables are defined"
  assert:
    that:
      - gitlab_api_url is defined
      - gitlab_api_token is defined
      - gitlab_group is defined
      - gitlab_project is defined
      - gitlab_validate_certs is defined
      - gitlab_api_user is defined
      - gitlab_default_branch is defined
      - gitlab_http_protocol is defined

- name: Set Git repo URL
  set_fact:
    gitlab_api_url: "{{ gitlab_http_protocol }}://{{ gitlab_api_user }}:{{ gitlab_api_token }}@{{ gitlab_api_url | regex_replace('http://|https://','') }}"

- name: Get Git repo ID
  ansible.builtin.uri:
    url: "{{ gitlab_api_url }}/api/v4/projects?search={{ gitlab_project_creation.project.path }}"
    method: GET
    status_code: 200
    return_content: true
    validate_certs: false
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
      Content-Type: application/json
  register: repo_id_res

- debug:
    msg:
      - "{{ repo_id_res.json }}"
      - "{{ repo_id_res.json[0] }}"
      - "{{ repo_id_res.json[0].id }}"

#    curl --request POST --header "PRIVATE-TOKEN: <your_access_token>" \
#    --header "Content-Type:application/json" \
#    --data '{ "name":"test_token", "scopes":["api", "read_repository"], "expires_at":"2021-01-31", "access_level": 30 }' \
#    "https://gitlab.example.com/api/v4/projects/<project_id>/access_tokens"

- name: Create an access token for the given project
  ansible.builtin.uri:
    url: "{{ gitlab_api_url }}/api/v4/projects/{{ repo_id_res.json[0].id }}/deploy_tokens/"
    method: POST
    #body: "{{ lookup('ansible.builtin.file','issue.json') }}"
    #body: '{"name": "CasC deploy token", "expires_at": "3000-01-01", "access_level": 50, "scopes": ["api"]}'
    body:
      name: "CasC deploy token"
      expires_at: "3000-01-01"
      access_level: 50
      scopes:
        - api
        - read_repository
    # status_code: 201
    body_format: json
    return_content: true
    validate_certs: false
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
      Content-Type: application/json
  register: repo_token_res

- debug:
    msg:
      - "{{ repo_token_res }}"
...
#    api_url: "{{ gitlab_api_url }}"
#    validate_certs: "{{ gitlab_validate_certs }}"
#    api_token: "{{  gitlab_api_token }}"
