- name: "Assert that all needed variables are defined"
  assert:
    that:
      - controller_hostname is defined
      - controller_username is defined
      - controller_password is defined
      - controller_validate_certs is defined
      - casc_organization is defined
      - workflow_job_template_name is defined or job_template_name is defined
      - gitlab_project is defined

- name: "Setup authentication (block)"
  block:
    - name: "Get the template related information"
      ansible.builtin.uri:
        url: "https://{{ controller_hostname }}/api/v2/{{ 'workflow_' if (is_workflow | bool) }}job_templates/?name={{ job_template_name | urlencode }}"
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        method: GET
        force_basic_auth: true
        validate_certs: "{{ controller_validate_certs }}"
        status_code: 200
      register: template_res

    - name: "Get the Webhook key"
      ansible.builtin.uri:
        url: "https://{{ controller_hostname }}/{{ template_res.json.results[0].related.webhook_key }}"
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        method: GET
        force_basic_auth: true
        validate_certs: "{{ controller_validate_certs }}"
        status_code: 200
      register: webhook_key_get

- name: "Set fact"
  set_fact:
    controller_webhook_url: "https://{{ controller_hostname }}/api/v2/{{ 'workflow_' if (is_workflow | bool) }}job_templates/{{ job_template_name | urlencode }}++{{ casc_organization }}/gitlab/"
    controller_webhook_key: "{{ webhook_key_get.json.webhook_key }}"

- name: "Adding a project hook"
  community.general.gitlab_hook:
    api_url: "{{ gitlab_api_url }}"
    api_token: "{{ gitlab_api_token | default(omit, true) }}"
    api_username: "{{ gitlab_api_user | default(omit, true) }}"
    api_password: "{{ gitlab_api_password | default(omit, true) }}"
    project: "{{ ( gitlab_group + '/' ) if (gitlab_group is defined and gitlab_group is not regex('^\\s*$')) else (gitlab_api_user + '/') }}{{ (gitlab_subgroup + '/') if (gitlab_subgroup is defined and gitlab_subgroup is not regex('^\\s*$')) else '' }}{{ gitlab_project }}"
    hook_url: "{{ controller_webhook_url }}"
    state: present
    push_events: "{{ gitlab_action_push }}"
    tag_push_events: "{{ gitlab_action_tag }}"
    hook_validate_certs: "{{ hook_validate_certs }}"
    token: "{{  controller_webhook_key }}"
    validate_certs: "{{ gitlab_validate_certs }}"
    push_events_branch_filter: "{{ gitlab_branch_filter | default(omit, true) }}"
