- name: "Assert that all needed variables are defined"
  assert:
    that:
      - gitlab_api_user is defined
      - gitlab_api_user_mail is defined

- name: Check if local changes exist in git
  command: git status
  args:
    chdir: "{{ gitlab_project_temp_dir }}"
  register: git_status

- block:
    - name: Git - Adding
      command: "git add *"
      args:
        chdir: "{{ gitlab_project_temp_dir }}"

    - name: Git - commiting
      command: git commit -m "First Commit - Basic Structure was created automatically"
      args:
        chdir: "{{ gitlab_project_temp_dir }}"
      environment:
        - GIT_COMMITTER_NAME: "{{ gitlab_api_user }}"
        - GIT_COMMITTER_EMAIL: "{{ gitlab_api_user_mail }}"
        - GIT_AUTHOR_NAME: "{{ gitlab_api_user }}"
        - GIT_AUTHOR_EMAIL: "{{ gitlab_api_user_mail }}"

    - name: Git - push
      command: git push
      args:
        chdir: "{{ gitlab_project_temp_dir }}"
      environment:
        - GIT_SSL_NO_VERIFY: "true"
  when: '"untracked files present" in git_status.stdout or "Changes not staged for commit" in git_status.stdout'

- name: Recursively remove temp directory
  ansible.builtin.file:
    path: "{{ gitlab_project_temp_dir }}"
    state: absent
