- name: "Create GitLab {{ gitlab_project }} Project"
  community.general.gitlab_project:
    api_url: "{{ gitlab_api_url }}"
    validate_certs: "{{ gitlab_validate_certs }}"
    api_token: "{{  gitlab_api_token }}"
    name: "{{ gitlab_project }}"
    group: "{{ gitlab_group }}/{{ gitlab_subgroup }}"
    initialize_with_readme: true
    default_branch:  "{{ gitlab_default_branch }}"
    visibility: "{{ gitlab_visibility }}"
  register: gitlab_project_creation

- name: Set git clone repo
  set_fact:
    gitlab_repo_clone: "{{ gitlab_http_protocol }}://{{ gitlab_api_user }}:{{ gitlab_api_token }}@{{ gitlab_api_url | regex_replace('http://|https://','') }}/{{ gitlab_project_creation.project.path_with_namespace}}.git"

- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: "{{ gitlab_repo_clone }}"
    dest: "{{ gitlab_project_temp_dir }}"
  environment:
      - GIT_SSL_NO_VERIFY: "true"
