---
# tasks file for gitlab_setup
- name: GitLab Init
  ansible.builtin.include_tasks: gitlab_init.yml
  args:
    apply:
      tags: git-init
  tags:
    - git-init

- name: GitLab Push
  ansible.builtin.include_tasks: gitlab_push.yml
  args:
    apply:
      tags: git-push
  tags:
    - git-push

- name: Create and protect branches
  ansible.builtin.include_tasks: create_branch.yml
  args:
    apply:
      tags: git-branches
  loop: "{{ gitlab_branches }}"
  loop_control:
    loop_var: __gitlab_branches_item
  tags:
    - git-branches

- name: Setup gitlab Webhook
  ansible.builtin.include_tasks: gitlab_webhook.yml
  args:
    apply:
      tags: git-hook
  tags:
    - git-hook
