---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    github_api_url: https://api.github.com
    github_url: https://github.com
    github_api_user_mail: agarciac@redhat.com
    github_api_user: adonisgarciac
    github_api_token: "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"
    github_repository: testrepo
    github_organization: adonisorg
    github_private: true
    github_http_protocol: https
    github_branches:
      - prod
      - dev
    org_dir_structure_parent:
      - { path: "collections", mode: '0755' }
      - { path: "group_vars", mode: '0755' }
      - { path: "group_vars/all", mode: '0755' }
      - { path: "images", mode: '0755' }
      - { path: "{{ dir_orgs_vars }}/{{ github_repository }}", mode: '0755' }
      - { path: "{{ dir_orgs_vars }}/{{ github_repository }}/env", mode: '0755' }
      - { path: "{{ dir_orgs_vars }}/{{ github_repository }}/env/common", mode: '0755' }
    other_template_list:
      - { template: casc_ctrl_config.yml.j2, dest:  casc_ctrl_config.yml }
      - { template: casc_ctrl_drop_diff.yml.j2, dest: casc_ctrl_drop_diff.yml }
      - { template: casc_ctrl_cd_webhook_trigger_github.yml.j2, dest: casc_ctrl_cd_webhook_trigger.yml }
      - { template: requirements.yml.j2, dest: collections/requirements.yml }
      - { template: README_github.md.j2, dest: README.md }
      - { template: gitignore.j2, dest: .gitignore }
      - { template: github_webhook.yml.j2, dest: github_webhook.yml }
      - { template: inventory.j2, dest: inventory }

  tasks:
    - name: GitHub init
      ansible.builtin.include_role:
        name: github_setup
        tasks_from: github_init.yml
        apply:
          tags: git-init
      tags: git-init

    - name: Create dir structure
      ansible.builtin.include_role:
        name: filetree_create
        tasks_from: filetree_create_github.yml
        apply:
          tags: filetree_create
      tags: filetree_create

    - name: GitHub push
      ansible.builtin.include_role:
        name: github_setup
        tasks_from: github_push.yml
        apply:
          tags: git-push
      tags: git-push
