---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    automation_hub: "demo-hub1-dev.testing.com"
    controller_dev: "demo-ctr1-dev.testing.com"
    controller_pro: "demo-ctr1-prd.testing.com"
    github_api_url: https://api.github.com
    github_url: https://github.com
    github_api_user_mail: ToDo
    github_api_user: ToDo
    github_api_token: "ToDo"
    github_repository: testrepo
    github_organization: org
    github_private: true
    github_http_protocol: https
    github_default_branch: prod
    github_branches:
      - prod
      - dev
    org_dir_structure_parent:
      - { path: ".github/workflows", mode: '0755' }
      - { path: "collections", mode: '0755' }
      - { path: "group_vars", mode: '0755' }
      - { path: "group_vars/all", mode: '0755' }
      - { path: "images", mode: '0755' }
      - { path: "{{ dir_orgs_vars }}/{{ gitlab_project }}", mode: '0755' }
      - { path: "{{ dir_orgs_vars }}/{{ gitlab_project }}/env", mode: '0755' }
      - { path: "{{ dir_orgs_vars }}/{{ gitlab_project }}/env/common", mode: '0755' }

  tasks:
    - name: GitHub init
      ansible.builtin.include_role:
        name: github_setup
        tasks_from: github_init.yml
        apply:
          tags: git-init
      tags: git-init

    - name: Create dir structure
      ansible.builtin.include_role:
        name: filetree_create
        tasks_from: filetree_create_github.yml
        apply:
          tags: filetree_create
      tags: filetree_create

    - name: GitHub push
      ansible.builtin.include_role:
        name: github_setup
        tasks_from: github_push.yml
        apply:
          tags: git-push
      tags: git-push
