---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    gitlab_api_url: https://gitlab.testing.com
    gitlab_validate_certs: false
    gitlab_api_user: aap-demo
    gitlab_api_token: "TOKEN_GITLAB"
    gitlab_group: gitlab_group
    gitlab_subgroup: gitlab_subgroup
    gitlab_project: gitlab_project
    gitlab_visibility: internal
    gitlab_default_branch: prod_casc
    gitlab_http_protocol: http
    gitlab_branches:
      - prod_casc
      - dev_casc

  tasks:
    - name: GitLab init
      ansible.builtin.include_role:
        name: gitlab_setup
        tasks_from: gitlab_init.yml
        apply:
          tags: git-init
      tags: git-init

    - name: Create dir structure
      ansible.builtin.include_role:
        name: filetree_create
        apply:
          tags: filetree_create
      tags: filetree_create

    - name: GitLab push
      ansible.builtin.include_role:
        name: gitlab_setup
        tasks_from: gitlab_push.yml
        apply:
          tags: git-push
      tags: git-push

    - name: GitLab push
      ansible.builtin.include_role:
        name: gitlab_setup
        tasks_from:  create_branch.yml
        apply:
          tags: git-branches
      loop: "{{ gitlab_branches }}"
      loop_control:
        loop_var: __gitlab_branches_item
      tags: git-branches
